amcl:
  ros__parameters:
    use_sim_time: true

    # TF frames
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    tf_broadcast: true
    transform_tolerance: 0.5

    # Topics
    scan_topic: "scan"

    # Motion model (omni / diff / etc). For this sim, diff-like is OK.
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # Update thresholds
    update_min_d: 0.05
    update_min_a: 0.05

    # Particle filter
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99

    # Laser model
    laser_model_type: "likelihood_field"
    laser_max_range: 15.0
    laser_min_range: 0.1
    max_beams: 60
    z_hit: 0.8
    z_short: 0.1
    z_max: 0.05
    z_rand: 0.05
    sigma_hit: 0.2
    lambda_short: 0.1

    # Likelihood field parameters
    laser_likelihood_max_dist: 2.0

    # Initial pose (can also be set from RViz2 '2D Pose Estimate')
    set_initial_pose: false
    always_reset_initial_pose: false

