<?xml version="1.0"?>
<robot name="tri_wheel_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================= 定义常量（方便修改） ========================= -->
  <xacro:property name="base_length" value="2.1" /> <!-- 车体长 -->
  <xacro:property name="base_width"  value="1.076" /> <!-- 车体宽 -->
  <xacro:property name="base_height" value="1.1" /> <!-- 车体高 -->
  <xacro:property name="base_mass" value="37" /> <!-- 车体质量 -->
  <xacro:property name="wheel_radius" value="0.21" /> <!-- 轮子半径 -->
  <xacro:property name="wheel_width"  value="0.15" /> <!-- 轮子厚度 -->
  <xacro:property name="steering_wheel_radius" value="0.195" /> <!-- 轮子半径 -->
  <xacro:property name="steering_wheel_width"  value="0.35" /> <!-- 轮子厚度 -->
  <xacro:property name="wheel_y_offset" value="0.463" /> <!-- 驱动轮到中心距离 -->
  <xacro:property name="drive_wheel_mass" value="20" /> <!-- 驱动轮质量 -->
  <xacro:property name="steering_wheel_mass" value="20" /> <!-- 转向轮质量 -->
  <xacro:property name="steering_link_mass" value="10" /> <!-- 转向连杆质量 -->
  
  <!-- ========================= 传感器参数 ========================= -->
  <xacro:property name="lidar_height" value="0.1" />      <!-- 激光雷达高度 -->
  <xacro:property name="lidar_radius" value="0.05" />     <!-- 激光雷达半径 -->
  <xacro:property name="camera_size" value="0.05" />      <!-- 相机尺寸 -->
  <xacro:property name="imu_size" value="0.02" />         <!-- IMU 尺寸 -->

  <!-- ========================= 添加虚拟根链接 ========================= -->
  <link name="base_footprint">
    <!-- 这个链接没有惯性，没有碰撞和视觉，只是一个参考点 -->
  </link>

  <!-- ========================= 定义车体连杆 (base_link) ========================= -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.4 0.8 1.0"/> <!-- 蓝色 -->
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/> <!-- 车体质量，单位：千克 -->
      <inertia ixx="${base_mass*(base_width*base_width + base_height*base_height)/12}" ixy="0.0" ixz="0.0" iyy="${base_mass*(base_length*base_length + (base_height)*(base_height))/12}" iyz="0.0" izz="${base_mass*(base_length*base_length + base_width*base_width)/12}"/>
    </inertial>
  </link>

  <!-- 添加固定关节连接虚拟根链接和base_link -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>
  
  <!-- ========================= 定义左驱动轮 ========================= -->
  <link name="left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="green">
       <color rgba="0.0 1.0 0.0 1.0"/> <!-- 绿色 -->
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${drive_wheel_mass}"/>
      <inertia ixx="${drive_wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)/12}" ixy="0.0" ixz="0.0" iyy="${drive_wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)/12}" iyz="0.0" izz="${drive_wheel_mass*wheel_radius*wheel_radius/2}"/>
    </inertial>
  </link>

  <!-- 左轮关节：连接车体与左轮，类型为 continuous（连续旋转）-->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0.616 ${wheel_y_offset} -${base_height/2}" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/> <!-- 绕Y轴旋转 -->
  </joint>

  <!-- ========================= 定义右驱动轮（与左轮对称） ========================= -->
  <link name="right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="green">
       <color rgba="0.0 1.0 0.0 1.0"/> <!-- 绿色 -->
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${drive_wheel_mass}"/>
      <inertia ixx="${drive_wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)/12}" ixy="0.0" ixz="0.0" iyy="${drive_wheel_mass*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)/12}" iyz="0.0" izz="${drive_wheel_mass*wheel_radius*wheel_radius/2}"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0.616 -${wheel_y_offset} -${base_height/2}" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- ========================= 定义前转向轮（可转向） ========================= -->
  <!-- 1. 转向臂连杆 (只是一个用于转向的连接杆) -->
  <link name="caster_steering_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.05" length="0.3"/> <!-- 一个小圆柱，表示转向臂 -->
        </geometry>
        <material name="gray">
            <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
    </visual>
    <inertial>
        <mass value="${steering_link_mass}"/>
      <inertia ixx="${steering_link_mass*(3*0.05*0.05 + 0.3*0.3)/12}" ixy="0.0" ixz="0.0" iyy="${steering_link_mass*(3*0.05*0.05 + 0.3*0.3)/12}" iyz="0.0" izz="${steering_link_mass*0.05*0.05/2}"/>
    </inertial>
  </link>

  <!-- 2. 转向轮（真正的轮子）连杆 -->
  <link name="caster_wheel_link">
    <visual>
        <geometry>
            <!-- 轮子：一个直立的圆柱，注意轴线是Z轴 -->
            <cylinder radius="${steering_wheel_radius}" length="${steering_wheel_width}"/>
        </geometry>
        <material name="gray">
            <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${steering_wheel_radius}" length="${steering_wheel_width}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="${steering_wheel_mass}"/>
      <inertia ixx="${steering_wheel_mass*(3*steering_wheel_radius*steering_wheel_radius + steering_wheel_width*steering_wheel_width)/12}" ixy="0.0" ixz="0.0" iyy="${steering_wheel_mass*steering_wheel_radius*steering_wheel_radius/2}" iyz="0.0" izz="${steering_wheel_mass*(3*steering_wheel_radius*steering_wheel_radius + steering_wheel_width*steering_wheel_width)/12}"/>
  </inertial>
  </link>

  <!-- 3. 转向关节：连接车体与转向臂，控制左右转向 (revolute，绕Z轴) -->
  <joint name="caster_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="caster_steering_link"/>
    <!-- 安装位置：车前部中间，略低于车体 -->
    <origin xyz="-0.855 0 -${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/> <!-- 绕Z轴旋转（水平转向） -->
    <!-- 限制转向角度，例如左右各75度（约1.31弧度） -->
    <limit lower="-1.57" upper="1.57" effort="500.0" velocity="1.0"/>
    <dynamics damping="1.0" friction="0.1"/>
  </joint>

  <!-- 4. 滚动关节：连接转向臂与轮子，控制轮子滚动 (continuous，绕轮子Y轴) -->
  <joint name="caster_wheel_joint" type="continuous">
    <parent link="caster_steering_link"/>
    <child link="caster_wheel_link"/>
    <!-- 将轮子安装在转向臂末端，并将其扶正（绕X轴转90度） -->
    <origin xyz="0 0 -0.015" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/> <!-- 轮子绕自己的Z轴旋转（滚动） -->
  </joint>

  <!-- ============================================================================ -->
  <!--                              传感器定义                                       -->
  <!-- ============================================================================ -->

  <!-- ========================= IMU 传感器 ========================= -->
  <!-- 
    IMU (惯性测量单元) 安装在车体中心
    输出：
    - 角速度 (gyroscope): rad/s
    - 线性加速度 (accelerometer): m/s²
    - 姿态 (orientation): 四元数
  -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="${imu_size} ${imu_size} ${imu_size}"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${imu_size} ${imu_size} ${imu_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ========================= 多线激光雷达 (3D LiDAR) ========================= -->
  <!-- 
    模拟 Velodyne VLP-16 或 Ouster OS1-32 类型的多线激光雷达
    安装在车顶中央，提供 360° 水平视角
    参数：
    - 水平视角: 360°
    - 垂直视角: -15° ~ +15° (共 16 线)
    - 最大距离: 100m
    - 更新频率: 10Hz
  -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="dark_gray">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <!-- 安装在车顶中央 -->
    <origin xyz="0 0 ${base_height/2 + lidar_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- ========================= 前置深度相机 (RGB-D Camera) ========================= -->
  <!-- 
    模拟 Intel RealSense D435 类型的深度相机
    安装在车体前方，用于近距离障碍物检测和视觉感知
    输出：
    - RGB 图像: 640x480 @ 30fps
    - 深度图像: 640x480 @ 30fps
    - 点云数据
  -->
  <link name="front_camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- 相机光学坐标系 (Z 朝前, X 朝右, Y 朝下) -->
  <link name="front_camera_optical_link"/>

  <joint name="front_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_camera_link"/>
    <!-- 安装在车体前方上部 -->
    <origin xyz="${base_length/2 - 0.05} 0 ${base_height/4}" rpy="0 0 0"/>
  </joint>

  <joint name="front_camera_optical_joint" type="fixed">
    <parent link="front_camera_link"/>
    <child link="front_camera_optical_link"/>
    <!-- 从 ROS 坐标系 (X前Y左Z上) 转换到相机光学坐标系 (Z前X右Y下) -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ========================= 后置相机 ========================= -->
  <!-- 用于倒车辅助和后方监控 -->
  <link name="rear_camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <link name="rear_camera_optical_link"/>

  <joint name="rear_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_camera_link"/>
    <!-- 安装在车体后方，朝后看 -->
    <origin xyz="${-base_length/2 + 0.05} 0 ${base_height/4}" rpy="0 0 ${pi}"/>
  </joint>

  <joint name="rear_camera_optical_joint" type="fixed">
    <parent link="rear_camera_link"/>
    <child link="rear_camera_optical_link"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ========================= 左侧相机 ========================= -->
  <link name="left_camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <link name="left_camera_optical_link"/>

  <joint name="left_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="left_camera_link"/>
    <origin xyz="0 ${base_width/2 - 0.05} ${base_height/4}" rpy="0 0 ${pi/2}"/>
  </joint>

  <joint name="left_camera_optical_joint" type="fixed">
    <parent link="left_camera_link"/>
    <child link="left_camera_optical_link"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ========================= 右侧相机 ========================= -->
  <link name="right_camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <link name="right_camera_optical_link"/>

  <joint name="right_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="right_camera_link"/>
    <origin xyz="0 ${-base_width/2 + 0.05} ${base_height/4}" rpy="0 0 ${-pi/2}"/>
  </joint>

  <joint name="right_camera_optical_joint" type="fixed">
    <parent link="right_camera_link"/>
    <child link="right_camera_optical_link"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ============================================================================ -->
  <!--                            Gazebo 物理属性                                    -->
  <!-- ============================================================================ -->
  
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo reference="left_wheel_link">
    <material>Gazebo/Green</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>10.0</kd>
  </gazebo>
  
  <gazebo reference="right_wheel_link">
    <material>Gazebo/Green</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>10.0</kd>
  </gazebo>
  
  <gazebo reference="caster_steering_link">
    <material>Gazebo/Grey</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>
  
  <gazebo reference="caster_wheel_link">
    <material>Gazebo/DarkGrey</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>10.0</kd>
  </gazebo>

  <!-- 传感器外观 -->
  <gazebo reference="imu_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="front_camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="rear_camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="left_camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="right_camera_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ============================================================================ -->
  <!--                            Gazebo 传感器插件                                  -->
  <!-- ============================================================================ -->

  <!-- ========================= IMU 传感器插件 ========================= -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <topic>imu</topic>
      <gz_frame_id>imu_link</gz_frame_id>
      <imu>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.0002</stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.0002</stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.0002</stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.017</stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.017</stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.017</stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- ========================= 3D 激光雷达插件 (模拟 16 线激光雷达) ========================= -->
  <gazebo reference="lidar_link">
    <sensor name="lidar_3d" type="gpu_lidar">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <topic>scan/points</topic>
      <gz_frame_id>lidar_link</gz_frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>1800</samples>        <!-- 水平采样点数 (0.2° 分辨率) -->
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle> <!-- -180° -->
            <max_angle>3.14159</max_angle>  <!-- +180° -->
          </horizontal>
          <vertical>
            <samples>32</samples>           <!-- 32 线激光雷达 -->
            <resolution>1</resolution>
            <min_angle>-0.5236</min_angle>  <!-- -30° -->
            <max_angle>0.1745</max_angle>   <!-- +10° (向下看多一些) -->
          </vertical>
        </scan>
        <range>
          <min>0.3</min>
          <max>100.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.02</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>

  <!-- ========================= 2D 激光雷达 (用于导航) ========================= -->
  <!-- 从 3D 点云中提取一个水平扫描平面用于 2D 导航 -->
  <gazebo reference="lidar_link">
    <sensor name="lidar_2d" type="gpu_lidar">
      <always_on>true</always_on>
      <update_rate>20</update_rate>
      <topic>scan</topic>
      <gz_frame_id>lidar_link</gz_frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.3</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>

  <!-- ========================= 前置深度相机插件 ========================= -->
  <gazebo reference="front_camera_link">
    <!-- RGB 相机 -->
    <sensor name="front_camera_rgb" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <topic>front_camera/image_raw</topic>
      <gz_frame_id>front_camera_optical_link</gz_frame_id>
      <camera>
        <horizontal_fov>1.047</horizontal_fov> <!-- 60° -->
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
    </sensor>

    <!-- 深度相机 -->
    <sensor name="front_camera_depth" type="depth_camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <topic>front_camera/depth</topic>
      <gz_frame_id>front_camera_optical_link</gz_frame_id>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R_FLOAT32</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>10.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <!-- ========================= 后置相机插件 ========================= -->
  <gazebo reference="rear_camera_link">
    <sensor name="rear_camera_rgb" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <topic>rear_camera/image_raw</topic>
      <gz_frame_id>rear_camera_optical_link</gz_frame_id>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <!-- ========================= 左侧相机插件 ========================= -->
  <gazebo reference="left_camera_link">
    <sensor name="left_camera_rgb" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <topic>left_camera/image_raw</topic>
      <gz_frame_id>left_camera_optical_link</gz_frame_id>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <!-- ========================= 右侧相机插件 ========================= -->
  <gazebo reference="right_camera_link">
    <sensor name="right_camera_rgb" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <topic>right_camera/image_raw</topic>
      <gz_frame_id>right_camera_optical_link</gz_frame_id>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

  <!-- ============================================================================ -->
  <!--                            Gazebo 控制器插件                                  -->
  <!-- ============================================================================ -->
  <!-- 注意: Sensors 和 IMU 系统插件已在世界文件 (test_world.sdf) 中定义 -->

  <!-- ========================= 差速驱动插件 ========================= -->
  <gazebo>
    <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_y_offset*2}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50.0</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <tf_topic>tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
    </plugin>
  </gazebo>

  <!-- ========================= 转向关节控制器 ========================= -->
  <gazebo>
    <plugin name="gz::sim::systems::JointPositionController" filename="gz-sim-joint-position-controller-system">
      <joint_name>caster_steering_joint</joint_name>
      <topic>caster_steering/set_position</topic>
      <initial_position>0.0</initial_position>
      <pid>
        <p>100.0</p>
        <i>0.1</i>
        <d>1.0</d>
      </pid>
    </plugin>
  </gazebo>

  <!-- ========================= 关节状态发布器 ========================= -->
  <gazebo>
    <plugin name="gz::sim::systems::JointStatePublisher" filename="gz-sim-joint-state-publisher-system">
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>caster_steering_joint</joint_name>
      <joint_name>caster_wheel_joint</joint_name>
      <update_rate>50.0</update_rate>
    </plugin>
  </gazebo>

</robot>
